schema_version: 1

context:
  version: "1.12.4"

package:
  name: talosctl
  version: ${{ version }}

source:
  url: https://github.com/siderolabs/talos/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2ed9dc0d227ebd3f473f6c8d23702bce977ce4a7d63556437218bdc2ef37cac4

build:
  number: 0
  script:
    - if: unix
      then: go build -v -o $PREFIX/bin/talosctl -ldflags="-s -w -X github.com/siderolabs/talos/pkg/machinery/version.Tag=v${{ version }}" ./cmd/talosctl
      else: go build -v -o %LIBRARY_BIN%\talosctl.exe -ldflags="-s -X github.com/siderolabs/talos/pkg/machinery/version.Tag=v${{ version }}" ./cmd/talosctl
    - go-licenses save ./cmd/talosctl --save_path ./library-licenses --ignore github.com/siderolabs/talos

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - package_contents:
      bin:
        - talosctl

about:
  homepage: https://github.com/talosctl/talosctl
  summary: "Talos Linux is an OS for Kubernetes"
  description: |
    Talos is a modern OS for running Kubernetes: secure, immutable, and minimal.
    Talos is fully open source.
    All system management is done via an API.
    `talosctl` is a command line tool which uses that API.
  license: MPL-2.0
  license_file:
    - LICENSE
    - library-licenses/
  documentation: https://docs.siderolabs.com/talos
  repository: https://github.com/siderolabs/talos

extra:
  recipe-maintainers:
    - phreed
