schema_version: 1

context:
  version: "1.13.6"

package:
  name: talosctl
  version: ${{ version }}

source:
  url: https://github.com/siderolabs/talos/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 8e08a279ef826c50e98ce8953dcc140d66f40c59922ab794d67b3e39f938f1f7

build:
  number: 0
  script:
    - if: unix
      then: find . \( -name go.mod -o -name go.work \) -exec sed -i 's/^go 1\.26\.[0-9]*/go 1.26.2/' {} +
      else: powershell -Command "Get-ChildItem -Recurse -Include go.mod,go.work | ForEach-Object { (Get-Content $_) -replace '^go 1\.26\.\d+', 'go 1.26.2' | Set-Content $_ }"
    - if: unix
      then: GOWORK=off go build -v -o $PREFIX/bin/talosctl -ldflags="-s -w -X github.com/siderolabs/talos/pkg/machinery/version.Tag=v${{ version }}" ./cmd/talosctl
      else: set GOWORK=off && go build -v -o %LIBRARY_BIN%\talosctl.exe -ldflags="-s -X github.com/siderolabs/talos/pkg/machinery/version.Tag=v${{ version }}" ./cmd/talosctl
    - go-licenses save ./cmd/talosctl --save_path ./library-licenses --ignore github.com/siderolabs/talos

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - package_contents:
      bin:
        - talosctl

about:
  homepage: https://github.com/talosctl/talosctl
  summary: "Talos Linux is an OS for Kubernetes"
  description: |
    Talos is a modern OS for running Kubernetes: secure, immutable, and minimal.
    Talos is fully open source.
    All system management is done via an API.
    `talosctl` is a command line tool which uses that API.
  license: MPL-2.0
  license_file:
    - LICENSE
    - library-licenses/
  documentation: https://docs.siderolabs.com/talos
  repository: https://github.com/siderolabs/talos

extra:
  recipe-maintainers:
    - phreed
